"""Reconstruct the 28 pre-registered hypotheses (H1–H15 / DH1–DH13) as data.

WHY THIS FILE EXISTS AND WHAT IT IS NOT
---------------------------------------
AC-6 asks for at least one insight that is NOT already in the author's
pre-existing hypothesis list. That test needs the list in a form a machine can
compare against — but the original prose lives in the blueprint PDF, not in
this repository. What the repository does hold, in `problemstatement.md` §5.7
and `codebook_v1.yaml`, is the **crosswalk**: every H and DH id mapped onto the
canonical codes that absorbed it.

So each prior is reconstructed as *the union of the claims its codes make*.
That is a deliberately GENEROUS reconstruction: an insight only counts as novel
if it fails to match anything in the entire deductive framework, which is a
stricter bar than matching a single hypothesis sentence. Reconstruction can
therefore make AC-6 harder to satisfy, never easier — the failure direction
that keeps the test honest (EC-INS-7: manufacturing novelty is the worst
available outcome).

The output is written to `codebook/priors_v1.yaml` and committed, so the thing
the novelty check compared against is inspectable rather than implied.
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from pipeline.common import codebook as cbm  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
PRIORS_PATH = ROOT / "codebook" / "priors_v1.yaml"

# The 28 ids AC-6 names. Listed explicitly rather than derived from whatever
# happens to appear in `blueprint_refs`, so a ref lost in a codebook edit fails
# loudly here instead of quietly shrinking the bar novelty has to clear.
EXPECTED = [f"H{i}" for i in range(1, 16)] + [f"DH{i}" for i in range(1, 14)]


def build() -> dict:
    cb = cbm.load()
    by_ref: dict[str, list[str]] = defaultdict(list)
    for cid, d in cb.codes.items():
        for ref in d.get("blueprint_refs") or []:
            by_ref[str(ref)].append(cid)

    missing = [h for h in EXPECTED if h not in by_ref]
    if missing:
        raise RuntimeError(
            f"blueprint_refs no longer cover {missing} — the novelty bar would be "
            "silently lowered. Restore the refs in codebook_v1.yaml.")

    priors = []
    for pid in EXPECTED:
        codes = by_ref[pid]
        # The prior's text has to be COMPARABLE IN SUBSTANCE to a generated
        # insight, or the similarity score measures sentence length instead of
        # meaning. A first version used only the code's name and question — four
        # or five words — and every insight came back "novel" with its nearest
        # prior on an unrelated code, which is a broken instrument reporting a
        # flattering result. Name, question, boundary note and the observable
        # workarounds give the embedding something to actually match against.
        parts = []
        for cid in codes:
            d = cb.codes[cid]
            q = str(d.get("question") or "").strip().strip('"')
            note = " ".join(str(d.get("boundary_note") or "").split())
            wk = d.get("workarounds") or []
            bit = f"{d['name']}"
            if q:
                bit += f". The unresolved question is: {q}"
            if note:
                bit += f". {note}"
            if wk:
                bit += f" People work around it by: {'; '.join(str(w) for w in wk)}."
            parts.append(bit)
        priors.append({
            "id": pid,
            "codes": codes,
            "statement": "Pre-registered barrier hypothesis. " + " ".join(parts),
            "stages": sorted({cb.codes[c]["stage"] for c in codes}),
        })
    return {
        "version": "priors_v1",
        "derived_from": {
            "codebook": cb.version_string,
            "source": "problemstatement.md §5.7 crosswalk + codebook_v1.yaml blueprint_refs",
        },
        "note": (
            "Reconstruction, not transcription. The blueprint's H/DH prose is not in "
            "this repository; each prior is the union of the claims made by the codes "
            "that absorbed it. Deliberately generous — a novel insight must miss the "
            "whole framework, not one sentence."
        ),
        "n_priors": len(priors),
        "priors": priors,
    }


def main() -> int:
    doc = build()
    PRIORS_PATH.write_text(
        "# GENERATED by pipeline/synthesise/priors.py — do not hand-edit.\n"
        "# The comparison corpus for the AC-6 novelty check (S3-MET-1).\n"
        + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100))
    print(f"{PRIORS_PATH.relative_to(ROOT)}: {doc['n_priors']} priors")
    for p in doc["priors"]:
        print(f"  {p['id']:<5} {','.join(p['codes']):<22} {p['statement'][:70]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
